name: 建立阿里雲節點

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: jerray/setup-aliyun-cli-action@v1.0.0
        with:
          aliyun-cli-version: '3.0.29'
          mode: AK
          access-key-id: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
          region: ${{ secrets.ALIYUN_REGION }}
      - run: aliyun oss rm oss://eric2788/scriptsettings -r -f
      - run: aliyun oss cp ./ oss://eric2788/scriptsettings -r -u